steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'linkedinClientId=${_LINKEDIN_CLIENT_ID}'
    - 'linkedinClientSecret=${_LINKEDIN_CLIENT_SECRET}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "600s"